#!/usr/bin/perl -l
#
# lxc-add nginx script
# Rootnode, http://rootnode.net
#
# Copyright (C) 2012 Marcin Hlybin
# All rights reserved.
#
# Nginx configuration

use warnings;
use strict;
use Readonly;

# Configuration
Readonly my $LXC_DIR  => '/lxc/user';
Readonly my @DIR_LIST => qw(
        var/run/nginx
        var/lock/nginx
        var/lib/nginx
	var/log/nginx
);

# Check paths
-d $LXC_DIR  or die "\$LXC_DIR ($LXC_DIR) not found.\n";

# Get arguments
die "Uneven number of arguments." if @ARGV % 2;
my %arg = @ARGV;

# Mandatory arguments
my $uid         = $arg{uid}         or die "Uid not specified.";
my $user_name   = $arg{user_name}   or die "User name not specified.";
my $server_no   = $arg{server_no}   or die "Server number not specified.";
my $server_type = $arg{server_type} or die "Server type not specified."; 
my $ipaddr      = $arg{ipaddr}      or die "IP address not specified.";

# Change permissions of nginx directories
system("find $LXC_DIR/$user_name/rootfs/home/etc/nginx -type d | xargs -i chmod 700 {}");
$? and die "Cannot change nginx directory permissions: $!";

# Change permissions of nginx files
system("find $LXC_DIR/$user_name/rootfs/home/etc/nginx -type f | xargs -i chmod 600 {}");
$? and die "Cannot change nginx file permissions: $!";

# Change owner of apache2 files
system("chown -R $uid:$uid $LXC_DIR/$user_name/rootfs/home/etc/nginx");
$? and die "Cannot change owner of nginx files: $!";

# Nginx user.conf
my $user_conf_file="$LXC_DIR/$user_name/rootfs/home/etc/nginx/user.conf";
unlink $user_conf_file;
open my $user_conf_fh, '>', $user_conf_file;
print $user_conf_fh "user $user_name $user_name";
close $user_conf_fh;

# Owner of /var directories
foreach my $dir_name (@DIR_LIST) {
        my $dir_path = "$LXC_DIR/$user_name/rootfs/home/$dir_name";
        if (!-d $dir_path) {
                mkdir $dir_path, 0700 or die "Cannot create dir '$dir_path'";
        }
        system("chown -R $uid:$uid $dir_path");
        $? and die "Cannot change owner of directory '$dir_path': $!";
}

# Configuration symlink in ~/etc
my $user_etc_dir = "$LXC_DIR/$user_name/rootfs/home/$user_name/etc";
if (!-l "$user_etc_dir/nginx") {
	my $symlink_dir = "$user_etc_dir/nginx";
	symlink '/etc/nginx', $symlink_dir or die "Cannot create symlink $symlink_dir";
}
