#!/usr/bin/perl -l
#
# lxc-add ssmtp script
# Rootnode, http://rootnode.net
#
# Copyright (C) 2012 Marcin Hlybin
# All rights reserved.
#
# The script creates SSMTP configuration

use warnings;
use strict;
use Readonly;

# Configuration
Readonly my $LXC_DIR => '/lxc/user';

# Check paths
-d $LXC_DIR or die "\$LXC_DIR ($LXC_DIR) not found.\n";

# Get arguments
die "Uneven number of arguments." if @ARGV % 2;
my %arg = @ARGV;

# Mandatory arguments
my $uid         = $arg{uid}         or die "Uid not specified.";
my $user_name   = $arg{user_name}   or die "User name not specified.";
my $server_no   = $arg{server_no}   or die "Server number not specified.";
my $server_type = $arg{server_type} or die "Server type not specified."; 
my $ssmtp_host  = $arg{ssmtp_host}  or die "SSMTP host not specified.";

# Remove ssmtp.conf file
my $ssmtp_file = "$LXC_DIR/$user_name/rootfs/home/etc/ssmtp/ssmtp.conf";
unlink $ssmtp_file;

# Create ssmtp.conf file
open my $ssmtp_fh, '>', $ssmtp_file or die "Cannot open ssmtp file ($ssmtp_file)";
print $ssmtp_fh <<EOF;
#
# Config file for sSMTP sendmail
#
# The person who gets all mail for userids < 1000
# Make this empty to disable rewriting.
root=postmaster

# The place where the mail goes. The actual machine name is required no 
# MX records are consulted. Commonly mailhosts are named mail.domain.com
mailhub=$ssmtp_host

# Where will the mail seem to come from?
#rewriteDomain=

# The full hostname
hostname=$server_type.$user_name.rootnode.net

# Are users allowed to set their own From: address?
# YES - Allow the user to specify their own From: address
# NO - Use the system generated From: address
FromLineOverride=YES
EOF

close $ssmtp_fh;
exit;
